"""PyMuPDF text extraction. Task 3.3.

PDFs are generated by PyMuPDF at test time (design.md Testing Strategy) --
no committed binary fixtures.
"""

from __future__ import annotations

import fitz

from hcd_sync.extract import build_extraction_fields, extract_text


def _make_pdf(text: str | None) -> bytes:
    """Build a minimal one-page PDF, with or without a text layer."""
    doc = fitz.open()
    page = doc.new_page()
    if text is not None:
        page.insert_text((72, 72), text)
    data = doc.tobytes()
    doc.close()
    return data


def test_extract_text_from_text_bearing_pdf() -> None:
    pdf_bytes = _make_pdf("Punta Alta, 27 de enero de 2.026\nOrdenanza 4457")
    result = extract_text(pdf_bytes)
    assert not result.is_empty
    assert "Ordenanza 4457" in result.text
    assert result.pages == 1


def test_extract_text_from_scanned_pdf_with_no_text_layer() -> None:
    """A page with no inserted text has no text layer -- the OCR-out-of-scope case."""
    pdf_bytes = _make_pdf(None)
    result = extract_text(pdf_bytes)
    assert result.is_empty
    assert result.text.strip() == ""
    assert result.pages == 1


def test_build_extraction_fields_text_bearing_yields_ok_with_text_path() -> None:
    pdf_bytes = _make_pdf("Ordenanza 4457 - Mesa de Gestion del Agua")
    status_fields, document_json = build_extraction_fields(
        doc_id="4457-Mesa-de-Gestion-del-Agua",
        number=4457,
        sha256="deadbeef",
        pdf_bytes=pdf_bytes,
        now="2026-08-05T00:00:00Z",
    )
    assert status_fields == {
        "status": "ok",
        "text_path": "data/documents/4457-Mesa-de-Gestion-del-Agua.json",
    }
    assert document_json is not None
    assert document_json["schema_version"] == 1
    assert document_json["doc_id"] == "4457-Mesa-de-Gestion-del-Agua"
    assert document_json["number"] == 4457
    assert document_json["sha256"] == "deadbeef"
    assert document_json["extracted_at"] == "2026-08-05T00:00:00Z"
    assert isinstance(document_json["extractor"], str)
    assert document_json["extractor"].startswith("pymupdf/")
    assert document_json["pages"] == 1
    assert "Ordenanza 4457" in document_json["text"]


def test_build_extraction_fields_scanned_yields_no_text_and_no_document_json() -> None:
    """A scanned PDF is never recorded as an error (design.md D13)."""
    pdf_bytes = _make_pdf(None)
    status_fields, document_json = build_extraction_fields(
        doc_id="Scanned-Doc",
        number=None,
        sha256="abc123",
        pdf_bytes=pdf_bytes,
        now="2026-08-05T00:00:00Z",
    )
    assert status_fields == {"status": "no_text", "text_path": None}
    assert status_fields["status"] != "error"
    assert document_json is None


def test_build_extraction_fields_whitespace_only_text_counts_as_no_text() -> None:
    pdf_bytes = _make_pdf("   \n\t  ")
    status_fields, document_json = build_extraction_fields(
        doc_id="X", number=None, sha256="x", pdf_bytes=pdf_bytes, now="2026-08-05T00:00:00Z"
    )
    assert status_fields["status"] == "no_text"
    assert document_json is None
